### PR TITLE
Swamy/few modifications

### PR DESCRIPTION
**Pull request by vishipayyallore**
## Purpose

1. Removed Unused usings.
2. Code Formatting.
3. Renamed the DbContext class name.
4. Also changed the database name to "ToDoDataStore"

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?
1. Removed Unused usings.
2. Code Formatting.
3. Renamed the DbContext class name.
4. Also changed the database name to "ToDoDataStore"

```
[ ] Bugfix
[ ] Feature
[X] Code style update (formatting, local variables)
[X] Refactoring (no functional changes, no API changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Comment by vishipayyallore** [comment]
Sumit - @sughosneo,
Good evening. I have raised this PR. Whom should I reach to get this reviewed? Please advise. Many thanks.

Regards,
Swamy

image

**Comment by vishipayyallore** [comment]
It was unable to create the migration in the Local SQL Server.

`Applying migration '20200423113402_InitialCreate'.
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (7ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE [Todo] (
          [ID] INTEGER NOT NULL IDENTITY,
          [Description] TEXT NULL,
          [CreatedDate] TEXT(48) NOT NULL,
          CONSTRAINT [PK_Todo] PRIMARY KEY ([ID])
      );`

image

**Comment by vishipayyallore** [comment]
Verified it locally with **A.** SQLite, and **B.** SQL Server

image

**Comment by vishipayyallore** [comment]
@msftgits @spboyer @cephalin 
Could you please review and let me know of any changes. Many thanks.

Regards,
Swamy

**Comment by spboyer** [comment]
The link on the README is namesd incorrect. Links to SQL Azure sample, not containers.

App Code looks good.

**Comment by vishipayyallore** [comment]
@spboyer 
Good afternoon. I did not modify the ReadMe.md file. Is there any action item from myside? Please advise. Many thanks.

Regards,
Swamy

**Comment by vishipayyallore** [comment]
@spboyer @msftgits @cephalin
Good morning. Are there any action items/changes from my side for this PR to get approved? Please advise. Many thanks.

Regards,
Swamy

**Comment by spboyer** [comment]
#sign-off

**Comment by vishipayyallore** [comment]
**[+]** @microsoftopensource

**Comment by vishipayyallore** [comment]
@spboyer @msftgits @cephalin @microsoftopensource 
Good morning. Hope you are doing great. I am **ever so sorry** if I am troubling you guys. Could someone please 1. Approve, and 2. Merge this pull request if there are no action items from my side? That will be of great help. Many thanks again!!!

Regards,
Swamy

**Review by IEvangelist — APPROVED** [review]

**Pull request closed without merging**
